"""empty message

Revision ID: 332f64f82092
Revises: 4d2418147c02
Create Date: 2024-01-25 02:52:43.194677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332f64f82092'
down_revision = '4d2418147c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
